#!/bin/sh

[ -f ~/.config/xprofile ] && . ~/.config/xprofile

#nnn file manager:
export NNN_COLORS='6537'
export NNN_BMS='h:~/;m:/media;e:/etc'
export NNN_PLUG='a:nnn_mpv_sel;b:setbg;s:imgview;t:_|st*;x:_chmod +x $nnn*'

while true; do
	/usr/local/bin/dwm 2> /dev/null
done
