#!/bin/bash

dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

#Startup:
remap &
#blueman-applet &
dunst &
systemctl --user import-envoironment DISPLAY
unclutter -b &
devmon --no-gui &
#picom &
dwmblocks &
mpd ~/.config/mpd/mpd.conf
setbg &
